spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
      resolve-lazily: true
  application:

    name: AEII
  datasource:
    url:  jdbc:mysql://localhost:3308/AEII?characterEncoding=utf8&useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.qq.com
    port: 465
    username: 2858712518@qq.com
    password: lzbticyvndvddecd
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
jwt:
  secret: yourjwtsecretkeydsafsafdadafgsgkmld9430jfow8ty382jwfoibewgfnmdsi983wdmaliskbdfi3qgdjpjajdkjlagsyjd8i2q8odp9jawbdbais
  expiration: 3600
  refreshExpiration: 604800  # 7天（单位：秒）
logging:
  charset:
    console: GBK
    file: GBK
  level:
    org:
      demo:
        artExaminationInformationInquiry: DEBUG
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 9091