spring:
  application:
    name: AEII
  datasource:
    url:  jdbc:mysql://localhost:3308/AEII?characterEncoding=utf8&useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
jwt:
  secret: yourjwtsecretkeydsafsafdadafgsgkmld9430jfow8ty382jwfoibewgfnmdsi983wdmaliskbdfi3qgdjpjajdkjlagsyjd8i2q8odp9jawbdbais
  expiration: 3600
logging:
  level:
    org:
      demo:
        artExaminationInformationInquiry: DEBUG
